### ISSUE TITLE
Styling for "proof" too loud?

### ISSUE THREAD

**Issue by jstac** [najuzilu/sphinxcontrib-prettyproof#14]
I vote to remove the red background for proof: https://sphinxcontrib-prettyproof.readthedocs.io/en/latest/syntax.html

I love the styling over everything else.  Theorems need to attract attention to themselves.

The same is not true of proofs.  Often they are skipped on first reading.  

I suggest a plain background and a light grey side bar.  

What do you think @najuzilu ?

**Comment by najuzilu** [comment]
I created a draft PR (#15) but would be happy to merge if others are okay with the style @jstac suggested. Personally, I prefer it over the red background. This is what the suggestion would look like when rendered:

<img width="822" alt="Screen Shot 2020-09-01 at 2 08 53 AM" src="https://user-images.githubusercontent.com/33075058/91780527-167e1580-ebf8-11ea-9092-a11e5360b31b.png">

**Comment by jstac** [comment]
I like it, thanks!

**Comment by najuzilu** [comment]
I went ahead an merged #15.
