### ISSUE TITLE
[BUG] Math Block `$$ $$` inside proof directive throws error

### ISSUE THREAD

**Issue by AakashGfude** [najuzilu/sphinxcontrib-prettyproof#2]
Using `$$ $$` for math block throws error for absence of id.
The error is specifically coming when sphinx tries to number the equation

![image](https://user-images.githubusercontent.com/6542997/91520850-af333d80-e939-11ea-9fec-e682e095fd23.png)

**Comment by AakashGfude** [comment]
My bad, the error comes for math_blocks with **targets** like in this example:
 
![image](https://user-images.githubusercontent.com/6542997/91524164-e60d5180-e941-11ea-9f24-545d05f200d7.png)

**Comment by najuzilu** [comment]
Thanks for the feedback @AakashGfude. This is an issue with the `proof:proof` directive.

**Comment by mmcky** [comment]
- [ ] add as a test case when writing a fix
