### ISSUE TITLE
Drop italics in proof body?

### ISSUE THREAD

**Issue by jstac** [najuzilu/sphinxcontrib-prettyproof#21]
Hi @najuzilu , thanks for the adjustments to {proof:proof} styling --- it looks better now.

(And thanks for great work on this project.  It makes a huge difference. It has increased my quality of life by a factor of at least seven.)

I suggest that we also drop the italics (see pic).  Traditionally, theorems are written in italics and proofs are not.

Long blocks of italics are hard to read.
![ital](https://user-images.githubusercontent.com/3887684/91890347-aa241480-ecd2-11ea-89bb-0ded93a95492.png)

**Comment by najuzilu** [comment]
Ah yes, I meant to add the italics to "Proof" only but forgot. Would that be better or would you suggest we remove italics from proofs entirely?

Also, would you prefer that I add italics to any of the other directories? LaTeX Overleaf uses italics for the following:
- theorems
- corollaries
- lemmas
- remarks

**Comment by jstac** [comment]
In my view, we should drop italics entirely.

If I look at Lemma 4 in the picture above, the color background is a very nice substitute for what would normally be italic text.  The same would be true for a theorem.  The color scheme provides all the necessary emphasis.  Having both is unnecessary.

Sometimes less is more `:-)`.
