### ISSUE TITLE
Plain background for examples?

### ISSUE THREAD

**Issue by jstac** [najuzilu/sphinxcontrib-prettyproof#22]
If we look at this image

![eg](https://user-images.githubusercontent.com/3887684/91894178-9ed3e780-ecd8-11ea-9428-250c90830bd0.png)

my feeling is that the example grabs too much attention.

The lemma (or theorem, or corollary, etc.) needs to take most of the attention, so that readers can skim through and see the main results quickly.

Examples are just to supplement.

I suggest we make the example a bit less attention-seeking by giving it a plain (no color) background.

(The side bar is good though, because it shows the extent of the example.)

**Comment by najuzilu** [comment]
Great suggestion @jstac! Is this what you have in mind?

<img width="791" alt="Screen Shot 2020-09-01 at 9 11 09 PM" src="https://user-images.githubusercontent.com/33075058/91895522-aa52ee80-ec97-11ea-8629-0336307e8298.png">

**Comment by jstac** [comment]
Perfect.  Thanks @najuzilu `:-)`

**Comment by mmcky** [comment]
@najuzilu your `css` skills are coming to the fore `:-)`
