### ISSUE TITLE
[DOC] Adding documentation for conjectures

### ISSUE THREAD

**Issue by AakashGfude** [najuzilu/sphinxcontrib-prettyproof#4]
At present, the documentation for conjectures is missing:

![image](https://user-images.githubusercontent.com/6542997/91672146-d5dab980-eb6f-11ea-948b-3d8aaa4b4cd0.png)

https://sphinxcontrib-prettyproof.readthedocs.io/en/latest/syntax.html#conjectures

**Comment by mmcky** [comment]
@AakashGfude just working on a PR for the `docs` so I will add this.

**Comment by mmcky** [comment]
I think this is just missing an example.

**Comment by AakashGfude** [comment]
@mmcky example, as well as the definition and syntax, and arguments it takes.

**Comment by najuzilu** [comment]
I was looking for a conjecture example on QuantEcon and forgot to include it. Thanks for the improvements @mmcky! I have already merged your changes so I'll go ahead and close this issue.
