### ISSUE TITLE
[DISC] `{proof:proof}` directive has `class` option?

### ISSUE THREAD

**Issue by AakashGfude** [najuzilu/sphinxcontrib-prettyproof#9]
In the code https://github.com/najuzilu/sphinxcontrib-prettyproof/blob/master/sphinxcontrib/prettyproof/directive.py#L112 , it looks like `proof:proof` takes a `class` option as well?

But in the docs, it doesn't https://sphinxcontrib-prettyproof.readthedocs.io/en/latest/syntax.html#proofs

**Comment by najuzilu** [comment]
Thanks for the feedback @AakashGfude. I plan to fix this when I roll out the rewritten proof directive.
